# fly.toml app configuration file generated for runtahepr-database on 2023-10-31T04:50:45+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "runtahepr-database"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="data"
  destination="/data"